import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta http-equiv='cache-control' content='no-cache' />
      <meta http-equiv='expires' content='0' />
      <meta http-equiv='pragma' content='no-cache' />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
